export const projects = [
  {
    title: 'GO - Weather App',
  description: "GO Weather App is a web-based application built using React and Javascript that provides users with up-to-date weather information. The app displays the temperature in Fahrenheit, humidity, feels like, temperature, wind speed, and the country where the user is currently located or the location they have entered. With this information, users can quickly check the weather conditions and plan their day accordingly. ",
  image: '/images/weatherApp.png  ',
  tags: ['React', 'JavaScript'],
  source: 'https://melodic-dieffenbachia-5c705b.netlify.app/',
  visit: 'https://github.com/OmeshSachethana/GO_WeatherApp_React',
  id: 0
  },
  {
    title: 'GO - Coding AI',
    description:"GO is a virtual assistant powered by the artificial intelligence. The configuration for this assistant uses the OpenAI key and the text-davinci-003 model. The aim of GO is to assist users in a multitude of tasks including answering questions, providing recommendations, and generating creative content. Its ability to comprehend natural language inputs such as text queries or prompts and generate human-like responses sets it apart.",
    image: '/images/coding.png',
    tags: ['Open AI', 'React'],
    source: 'https://github.com/OmeshSachethana/GO---Coding-AI.git',
    visit: 'https://github.com/OmeshSachethana/GO---Coding-AI.git',
    id: 1,
  },
  {
    title: 'Article Summarizer',
    description: "Summarizrr is a tool that makes reading easier by summarizing long articles into simple and concise summaries. It is an open-source software that helps readers to understand the main points of an article without going through the entire content. Users can paste the article or website link into the search box, and Summarizrr will provide a summary that is easy to comprehend.",
      image: '/images/summarizrr.png',
      tags: ['React', 'JavaScript', 'Redux-toolkit'],
    source: 'https://article-summarizer-ai.netlify.app/',
    visit: 'https://github.com/OmeshSachethana/Article_Summarizer_AI',
    id: 2,
  },
  {
    title: 'Ceylon Voyages',
    description: "Discover Sri Lanka like never before with our innovative tourism application. Personalized profiles, easy tour bookings, inspiring travel blogs, and valuable feedback features are all at your fingertips. To inspire and inform travelers, our platform hosts a vibrant community of travel bloggers. Join us in promoting Sri Lanka's wonders and create unforgettable memories.",
    image: '/images/ceylonVoyages.png',
    tags: ['React(Vite)', 'Node', 'Express', 'MongoDB'],
    source: 'https://af-project-beta.vercel.app/tours',
    visit: 'https://github.com/OmeshSachethana/Ceylon_Voyages',
    id: 3,
  },
  {
    title: 'MERN Shopping Cart',
    description: "The mobile responsive shopping cart desktop application is a modern and user-friendly software developed using the MERN stack. It utilizes Redux for efficient state management and offers a seamless shopping experience. With a responsive design, it adapts to different devices and screen sizes. The application includes features such as user authentication, product catalog, search and filtering, secure payment options, and order tracking. It provides a convenient and interactive platform for online shopping.",
    image: '/images/mern_cart.png',
    tags: ['Next', 'Redux', 'MongoDB'],
    source: 'https://github.com/OmeshSachethana/MERN_ShoppingCart.git',
    visit: 'https://github.com/OmeshSachethana/MERN_ShoppingCart.git',
    id: 4,
  },
  {
    title: 'Shoes Landing Page',
    description: "The 'Sneakers' website sets the standard for seamless user experiences with its fully mobile-responsive design and exceptional user-friendliness.Developed using the dynamic combination of React and ViteJs, the site ensures swift performance and a seamless browsing experience.The aesthetic finesse is further enhanced by the use of Tailwind CSS for styling, resulting in a harmonious blend of aesthetics and usability.'Sneakers' website offers a delightful and effortless journey through its impressive collection.",
    image: '/images/shoe_landing_page.png',
    tags: ['React', 'ViteJs', 'TailwindCSS'],
    source: 'https://go-sneakers.netlify.app/',
    visit: 'https://github.com/OmeshSachethana/Shoes_LandingPage.git',
    id: 4,
  },
  {
    title: 'Constro Mobile Version',
    description: "Constro is a versatile application with both mobile and web platforms.  The technology caters to procurement management in the construction industry, a critical aspect of the sector. It facilitates the acquisition of building supplies for construction sites, streamlining the process. This involves selecting suppliers, negotiating prices, placing orders, invoicing, and delivering goods. ",
    image: '/images/constro_m.png',
    tags: ['Flutter', 'Firebase'],
    source: 'https://github.com/OmeshSachethana/CSSE_Project_Mobile',
    visit: 'https://github.com/OmeshSachethana/CSSE_Project_Mobile',
    id: 5,
  },
  {
    title: 'Constro Web Version',
    description: "Constro is a versatile application with both mobile and web platforms.  The technology caters to procurement management in the construction industry, a critical aspect of the sector. It facilitates the acquisition of building supplies for construction sites, streamlining the process. This involves selecting suppliers, negotiating prices, placing orders, invoicing, and delivering goods. ",
    image: '/images/constro_w.png',
    tags: ['MERN Stack', 'ViteJs', 'TailwindCSS', 'MUI'],
    source: 'https://github.com/OmeshSachethana/CSSE_Project_Web',
    visit: 'https://github.com/OmeshSachethana/CSSE_Project_Web',
    id: 6,
  },
  {
    title: 'GazeGenius',
    description: "The GazeGenius application is a comprehensive platform encompass functionalities such as Visual Fatigue Disorder (VFD) assessment, Contrast Sensitivity testing, Color Blindness evaluation, and a suite of engaging Eye Games tailored for children. Additionally, it offers an interactive quiz designed to captivate young users, all seamlessly managed through an intuitive Application Management system.  ",
    image: '/images/gazegenius.png',
    tags: ['Flutter', 'Firebase'],
    source: 'https://github.com/OmeshSachethana/SPM_Project',
    visit: 'https://github.com/OmeshSachethana/SPM_Project',
    id: 7,
  }, 
  {
    title: 'SustainSwap',
    description: "The “SustainSwap” is a mobile application designed to address the growing concern of fast fashion's environmental impact. It promotes a circular economy, curbing the industry's carbon footprint, and aims to democratize sustainable fashion, fostering a community of eco-conscious individuals. The app emphasizes convenience, user-friendliness, and tracks social and environmental impact. ",
    image: '/images/sustainswap.png',
    tags: ['Flutter', 'Firebase'],
    source: 'https://github.com/OmeshSachethana/UEE_Project',
    visit: 'https://github.com/OmeshSachethana/UEE_Project',
    id: 8,
  },

  
];

export const TimeLineData = [
  { year: 2019, text: 'I began my journey to become a software developer and created a mobile game using the Unity game engine, which I deployed to the Play Store.', },
  { year: 2020, text: 'I started creating the front-end of web applications using HTML and CSS.', },
  { year: 2021, text: 'I acquired proficiency in programming languages such as C, C++, JavaScript, and Java. With a team of four members from my university, I developed a web application called Online Bidding System.', },
  { year: 2022, text: 'I created UML diagrams, including use case, activity, sequence, communication, state machine, component, deployment, and class diagrams, and also gained knowledge in Object-Oriented Programming', },
  { year: 2023, text: "Gained expertise in MERN stack with Vite JS, AngularJS, SpringBoot and presently, I'm actively engaged in mastering Flutter for mobile app development. Exciting learning journey ahead!", },
];